"use client";

import { useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import { Id } from "../../convex/_generated/dataModel";
import {
  FileText,
  FileSpreadsheet,
  Presentation,
  Download,
  ExternalLink,
  Folder,
  Search,
  Filter,
} from "lucide-react";
import { useState } from "react";

interface DocumentsPageProps {
  userId: Id<"users">;
}

export function DocumentsPage({ userId }: DocumentsPageProps) {
  const documents = useQuery(api.documents.list, { userId });
  const [searchQuery, setSearchQuery] = useState("");
  const [filterType, setFilterType] = useState<string>("all");

  const getDocumentIcon = (type: string) => {
    switch (type) {
      case "docx":
        return <FileText className="h-5 w-5" style={{ color: "var(--accent)" }} />;
      case "xlsx":
        return <FileSpreadsheet className="h-5 w-5" style={{ color: "var(--success)" }} />;
      case "pptx":
        return <Presentation className="h-5 w-5" style={{ color: "var(--warning)" }} />;
      case "pdf":
        return <FileText className="h-5 w-5" style={{ color: "var(--error)" }} />;
      default:
        return <FileText className="h-5 w-5" style={{ color: "var(--text-tertiary)" }} />;
    }
  };

  const getDocumentTypeLabel = (type: string) => {
    switch (type) {
      case "docx":
        return "Word Document";
      case "xlsx":
        return "Excel Workbook";
      case "pptx":
        return "PowerPoint Presentation";
      case "pdf":
        return "PDF Document";
      default:
        return "Document";
    }
  };

  const formatFileSize = (bytes?: number) => {
    if (!bytes) return "Unknown size";
    const units = ["B", "KB", "MB", "GB"];
    let size = bytes;
    let unitIndex = 0;
    while (size >= 1024 && unitIndex < units.length - 1) {
      size /= 1024;
      unitIndex++;
    }
    return `${size.toFixed(unitIndex === 0 ? 0 : 1)} ${units[unitIndex]}`;
  };

  const formatDateTime = (timestamp: number) => {
    const date = new Date(timestamp);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffDays = diffMs / (1000 * 60 * 60 * 24);

    if (diffDays < 1) {
      return date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
    } else if (diffDays < 7) {
      return date.toLocaleDateString([], { weekday: "short", hour: "2-digit", minute: "2-digit" });
    }
    return date.toLocaleDateString([], {
      month: "short",
      day: "numeric",
      year: date.getFullYear() !== now.getFullYear() ? "numeric" : undefined,
    });
  };

  const filteredDocuments = documents?.filter((doc) => {
    const matchesSearch = doc.name.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesFilter = filterType === "all" || doc.type === filterType;
    return matchesSearch && matchesFilter;
  });

  const documentTypeStats =
    documents?.reduce(
      (acc, doc) => {
        acc[doc.type] = (acc[doc.type] || 0) + 1;
        return acc;
      },
      {} as Record<string, number>
    ) || {};

  if (!documents) {
    return (
      <div className="flex items-center justify-center p-8">
        <div className="text-center animate-fade-in">
          <Folder className="mx-auto mb-4 h-12 w-12 animate-pulse" style={{ color: "var(--text-ghost)" }} />
          <p style={{ color: "var(--text-ghost)" }}>Loading documents...</p>
        </div>
      </div>
    );
  }

  if (documents.length === 0) {
    return (
      <div className="animate-fade-in p-8 text-center">
        <Folder className="mx-auto mb-4 h-16 w-16" style={{ color: "var(--text-ghost)" }} />
        <h3 className="mb-2 text-lg font-semibold" style={{ color: "var(--text-primary)" }}>
          No documents yet
        </h3>
        <p className="mb-4 text-sm" style={{ color: "var(--text-tertiary)" }}>
          Documents generated by your M365 Operator will appear here.
        </p>
        <div className="flex items-center justify-center space-x-4 text-sm" style={{ color: "var(--text-ghost)" }}>
          <div className="flex items-center space-x-1">
            <FileText className="h-4 w-4" />
            <span>Word</span>
          </div>
          <div className="flex items-center space-x-1">
            <FileSpreadsheet className="h-4 w-4" />
            <span>Excel</span>
          </div>
          <div className="flex items-center space-x-1">
            <Presentation className="h-4 w-4" />
            <span>PowerPoint</span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="animate-fade-in space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1
            className="text-2xl font-bold"
            style={{ color: "var(--text-primary)", letterSpacing: "-0.025em" }}
          >
            Documents
          </h1>
          <p className="mt-1 text-sm" style={{ color: "var(--text-tertiary)" }}>
            {documents.length} document{documents.length !== 1 ? "s" : ""} generated
          </p>
        </div>

        {/* Stats */}
        <div className="flex items-center space-x-4 text-sm">
          {Object.entries(documentTypeStats).map(([type, count]) => (
            <div key={type} className="flex items-center space-x-1.5" style={{ color: "var(--text-tertiary)" }}>
              {getDocumentIcon(type)}
              <span>{String(count)}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Search and Filter */}
      <div className="flex items-center space-x-3">
        <div className="relative max-w-md flex-1">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2" style={{ color: "var(--text-ghost)" }} />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search documents..."
            className="focus-ring w-full rounded-lg py-2.5 pl-10 pr-4 text-sm transition-colors duration-150"
            style={{
              background: "var(--bg-surface)",
              border: "1px solid var(--border)",
              color: "var(--text-primary)",
            }}
            onFocus={(e) => {
              e.currentTarget.style.borderColor = "var(--accent)";
              e.currentTarget.style.boxShadow = "0 0 0 3px var(--accent-ring)";
            }}
            onBlur={(e) => {
              e.currentTarget.style.borderColor = "var(--border)";
              e.currentTarget.style.boxShadow = "";
            }}
          />
        </div>

        <div className="relative">
          <Filter className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2" style={{ color: "var(--text-ghost)" }} />
          <select
            value={filterType}
            onChange={(e) => setFilterType(e.target.value)}
            className="focus-ring appearance-none rounded-lg py-2.5 pl-10 pr-8 text-sm transition-colors duration-150"
            style={{
              background: "var(--bg-surface)",
              border: "1px solid var(--border)",
              color: "var(--text-primary)",
            }}
          >
            <option value="all">All Types</option>
            <option value="docx">Word Documents</option>
            <option value="xlsx">Excel Workbooks</option>
            <option value="pptx">PowerPoint</option>
            <option value="pdf">PDF Files</option>
          </select>
        </div>
      </div>

      {/* Documents Grid */}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
        {filteredDocuments?.map((document, i) => (
          <div
            key={document._id}
            className="animate-slide-up rounded-xl p-4 transition-all duration-150"
            style={{
              background: "var(--bg-surface)",
              border: "1px solid var(--border)",
              boxShadow: "var(--shadow-sm)",
              animationDelay: `${Math.min(i * 50, 300)}ms`,
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.borderColor = "var(--border-hover)";
              e.currentTarget.style.boxShadow = "var(--shadow-md)";
              e.currentTarget.style.transform = "translateY(-1px)";
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.borderColor = "var(--border)";
              e.currentTarget.style.boxShadow = "var(--shadow-sm)";
              e.currentTarget.style.transform = "";
            }}
          >
            <div className="mb-3 flex items-start justify-between">
              <div className="flex items-center space-x-3">
                {getDocumentIcon(document.type)}
                <div className="min-w-0 flex-1">
                  <h3 className="truncate text-sm font-medium" style={{ color: "var(--text-primary)" }}>
                    {document.name}
                  </h3>
                  <p className="text-xs" style={{ color: "var(--text-ghost)" }}>
                    {getDocumentTypeLabel(document.type)}
                  </p>
                </div>
              </div>
            </div>

            <div className="mb-4 space-y-2">
              <div className="flex items-center justify-between text-xs" style={{ color: "var(--text-ghost)" }}>
                <span>Created</span>
                <span>{formatDateTime(document.createdAt)}</span>
              </div>
              <div className="flex items-center justify-between text-xs" style={{ color: "var(--text-ghost)" }}>
                <span>Size</span>
                <span>{formatFileSize(document.size)}</span>
              </div>
            </div>

            {/* Actions */}
            <div className="flex items-center space-x-2 pt-3" style={{ borderTop: "1px solid var(--border)" }}>
              {document.webUrl ? (
                <a
                  href={document.webUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex flex-1 items-center justify-center space-x-1.5 rounded-lg px-3 py-2 text-xs font-medium transition-colors duration-150"
                  style={{
                    background: "var(--accent-bg)",
                    color: "var(--accent)",
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.background = "var(--accent-bg-hover)";
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.background = "var(--accent-bg)";
                  }}
                >
                  <ExternalLink className="h-3.5 w-3.5" />
                  <span>Open in Browser</span>
                </a>
              ) : (
                <button
                  disabled
                  className="flex flex-1 cursor-not-allowed items-center justify-center space-x-1.5 rounded-lg px-3 py-2 text-xs opacity-40"
                  style={{ background: "var(--bg-muted)", color: "var(--text-ghost)" }}
                >
                  <Download className="h-3.5 w-3.5" />
                  <span>Processing...</span>
                </button>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* Empty filtered results */}
      {filteredDocuments?.length === 0 && documents.length > 0 && (
        <div className="p-8 text-center">
          <Search className="mx-auto mb-4 h-12 w-12" style={{ color: "var(--text-ghost)" }} />
          <h3 className="mb-2 text-lg font-semibold" style={{ color: "var(--text-primary)" }}>
            No documents found
          </h3>
          <p className="text-sm" style={{ color: "var(--text-tertiary)" }}>
            Try adjusting your search or filter criteria.
          </p>
          <button
            onClick={() => {
              setSearchQuery("");
              setFilterType("all");
            }}
            className="mt-4 text-sm font-medium transition-colors duration-150"
            style={{ color: "var(--accent)" }}
          >
            Clear filters
          </button>
        </div>
      )}
    </div>
  );
}
