"use client";

import { useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import { Id } from "../../convex/_generated/dataModel";
import {
  FileText,
  FileSpreadsheet,
  Presentation,
  Download,
  ExternalLink,
  Calendar,
  Folder,
  Search,
  Filter,
} from "lucide-react";
import { useState } from "react";

interface DocumentsPageProps {
  userId: Id<"users">;
}

export function DocumentsPage({ userId }: DocumentsPageProps) {
  const documents = useQuery(api.documents.list, { userId });
  const [searchQuery, setSearchQuery] = useState("");
  const [filterType, setFilterType] = useState<string>("all");

  const getDocumentIcon = (type: string) => {
    switch (type) {
      case "docx":
        return <FileText className="w-5 h-5 text-blue-600" />;
      case "xlsx":
        return <FileSpreadsheet className="w-5 h-5 text-green-600" />;
      case "pptx":
        return <Presentation className="w-5 h-5 text-orange-600" />;
      case "pdf":
        return <FileText className="w-5 h-5 text-red-600" />;
      default:
        return <FileText className="w-5 h-5 text-gray-600" />;
    }
  };

  const getDocumentTypeLabel = (type: string) => {
    switch (type) {
      case "docx":
        return "Word Document";
      case "xlsx":
        return "Excel Workbook";
      case "pptx":
        return "PowerPoint Presentation";
      case "pdf":
        return "PDF Document";
      default:
        return "Document";
    }
  };

  const formatFileSize = (bytes?: number) => {
    if (!bytes) return "Unknown size";
    
    const units = ["B", "KB", "MB", "GB"];
    let size = bytes;
    let unitIndex = 0;
    
    while (size >= 1024 && unitIndex < units.length - 1) {
      size /= 1024;
      unitIndex++;
    }
    
    return `${size.toFixed(unitIndex === 0 ? 0 : 1)} ${units[unitIndex]}`;
  };

  const formatDateTime = (timestamp: number) => {
    const date = new Date(timestamp);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffDays = diffMs / (1000 * 60 * 60 * 24);

    if (diffDays < 1) {
      return date.toLocaleTimeString([], {
        hour: '2-digit',
        minute: '2-digit'
      });
    } else if (diffDays < 7) {
      return date.toLocaleDateString([], {
        weekday: 'short',
        hour: '2-digit',
        minute: '2-digit'
      });
    }
    
    return date.toLocaleDateString([], {
      month: 'short',
      day: 'numeric',
      year: date.getFullYear() !== now.getFullYear() ? 'numeric' : undefined
    });
  };

  const filteredDocuments = documents?.filter((doc) => {
    const matchesSearch = doc.name.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesFilter = filterType === "all" || doc.type === filterType;
    return matchesSearch && matchesFilter;
  });

  const documentTypeStats = documents?.reduce((acc, doc) => {
    acc[doc.type] = (acc[doc.type] || 0) + 1;
    return acc;
  }, {} as Record<string, number>) || {};

  if (!documents) {
    return (
      <div className="flex items-center justify-center p-8">
        <div className="text-center">
          <Folder className="w-12 h-12 text-gray-400 mx-auto mb-4 animate-pulse" />
          <p className="text-gray-600">Loading documents...</p>
        </div>
      </div>
    );
  }

  if (documents.length === 0) {
    return (
      <div className="text-center p-8">
        <Folder className="w-16 h-16 text-gray-300 mx-auto mb-4" />
        <h3 className="text-lg font-medium text-gray-900 mb-2">No documents yet</h3>
        <p className="text-gray-500 mb-4">
          Documents generated by your M365 Operator will appear here.
        </p>
        <div className="flex items-center justify-center space-x-4 text-sm text-gray-400">
          <div className="flex items-center space-x-1">
            <FileText className="w-4 h-4" />
            <span>Word</span>
          </div>
          <div className="flex items-center space-x-1">
            <FileSpreadsheet className="w-4 h-4" />
            <span>Excel</span>
          </div>
          <div className="flex items-center space-x-1">
            <Presentation className="w-4 h-4" />
            <span>PowerPoint</span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-semibold text-gray-900">Documents</h2>
          <p className="text-gray-600 mt-1">
            {documents.length} document{documents.length !== 1 ? "s" : ""} generated
          </p>
        </div>
        
        {/* Stats */}
        <div className="flex items-center space-x-4 text-sm">
          {Object.entries(documentTypeStats).map(([type, count]) => (
            <div key={type} className="flex items-center space-x-1 text-gray-600">
              {getDocumentIcon(type)}
              <span>{String(count)}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Search and Filter */}
      <div className="flex items-center space-x-4">
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search documents..."
            className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
          />
        </div>
        
        <div className="relative">
          <Filter className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" />
          <select
            value={filterType}
            onChange={(e) => setFilterType(e.target.value)}
            className="pl-10 pr-8 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white"
          >
            <option value="all">All Types</option>
            <option value="docx">Word Documents</option>
            <option value="xlsx">Excel Workbooks</option>
            <option value="pptx">PowerPoint</option>
            <option value="pdf">PDF Files</option>
          </select>
        </div>
      </div>

      {/* Documents Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {filteredDocuments?.map((document) => (
          <div
            key={document._id}
            className="bg-white border border-gray-200 rounded-lg p-4 hover:shadow-md transition-shadow"
          >
            <div className="flex items-start justify-between mb-3">
              <div className="flex items-center space-x-3">
                {getDocumentIcon(document.type)}
                <div className="min-w-0 flex-1">
                  <h3 className="text-sm font-medium text-gray-900 truncate">
                    {document.name}
                  </h3>
                  <p className="text-xs text-gray-500">
                    {getDocumentTypeLabel(document.type)}
                  </p>
                </div>
              </div>
            </div>

            <div className="space-y-2 mb-4">
              <div className="flex items-center justify-between text-xs text-gray-500">
                <span>Created</span>
                <span>{formatDateTime(document.createdAt)}</span>
              </div>
              
              <div className="flex items-center justify-between text-xs text-gray-500">
                <span>Size</span>
                <span>{formatFileSize(document.size)}</span>
              </div>
            </div>

            {/* Actions */}
            <div className="flex items-center space-x-2 pt-3 border-t border-gray-100">
              {document.webUrl ? (
                <a
                  href={document.webUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center space-x-1 px-3 py-1.5 text-xs text-blue-700 bg-blue-50 hover:bg-blue-100 rounded-lg transition-colors flex-1 justify-center"
                >
                  <ExternalLink className="w-3 h-3" />
                  <span>Open in Browser</span>
                </a>
              ) : (
                <button
                  disabled
                  className="flex items-center space-x-1 px-3 py-1.5 text-xs text-gray-400 bg-gray-50 rounded-lg cursor-not-allowed flex-1 justify-center"
                >
                  <Download className="w-3 h-3" />
                  <span>Processing...</span>
                </button>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* Empty filtered results */}
      {filteredDocuments?.length === 0 && documents.length > 0 && (
        <div className="text-center p-8">
          <Search className="w-12 h-12 text-gray-300 mx-auto mb-4" />
          <h3 className="text-lg font-medium text-gray-900 mb-2">No documents found</h3>
          <p className="text-gray-500">
            Try adjusting your search or filter criteria.
          </p>
          <button
            onClick={() => {
              setSearchQuery("");
              setFilterType("all");
            }}
            className="mt-4 text-blue-600 hover:text-blue-700 text-sm"
          >
            Clear filters
          </button>
        </div>
      )}
    </div>
  );
}